version: '3.8'

services:
  web:
    build: ./itmo_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./itmo_web:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=itmo_django
      - POSTGRES_PASSWORD=itmo_django
      - POSTGRES_DB=itmo_django_dev
volumes:
  postgres_data:
